# Generated by Django 5.0.3 on 2026-04-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_alter_shipmentorder_hold_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentReceipt',
        ),
    ]
