# Generated by Django 5.0.3 on 2026-04-28 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_delete_shipmentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='auto_update_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='auto_update_interval_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='auto_update_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='auto_update_percent_step',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='current_waypoint_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='route_waypoints',
            field=models.TextField(blank=True, default='', help_text='Optional intermediate stops, one per line.'),
        ),
    ]
